#!/usr/bin/env python3
"""
Generate code from GitHub issue using Claude on Bedrock.
Creates a PR with the generated code.
"""

import os
import json
import subprocess
import sys
import requests
from datetime import datetime


def get_bearer_token_and_region():
    """Get AWS credentials from environment."""
    bearer_token = os.getenv("AWS_BEARER_TOKEN")
    aws_region = os.getenv("AWS_REGION", "us-east-1")

    if not bearer_token:
        raise ValueError("AWS_BEARER_TOKEN environment variable is required")

    return bearer_token, aws_region


def generate_code_with_claude(issue_title: str, issue_body: str) -> str:
    """Use Claude to generate code based on issue description."""
    bearer_token, aws_region = get_bearer_token_and_region()

    prompt = f"""You are an expert developer. Based on the GitHub issue below, generate the complete code changes needed to solve it.

**Issue Title:** {issue_title}

**Issue Description:**
{issue_body}

Please:
1. Analyze what needs to be implemented
2. Generate complete, working code
3. Include all necessary files or changes
4. Follow best practices for the project

Return ONLY the code/changes. Be specific and complete."""

url = f"https://bedrock-runtime.{aws_region}.amazonaws.com/inference-profiles/us.anthropic.claude-3-haiku-20240307-v1:0/invoke"
    headers = {
        "Authorization": f"Bearer {bearer_token}",
        "Content-Type": "application/json",
    }

    body = {
        "anthropic_version": "bedrock-2023-06-01",
        "max_tokens": 4096,
        "messages": [
            {"role": "user", "content": prompt}
        ]
    }

    response = requests.post(url, json=body, headers=headers, timeout=60)

    if response.status_code != 200:
        raise RuntimeError(f"Bedrock API error: {response.status_code} - {response.text}")

    result = response.json()
    response_text = ""

    if "content" in result:
        for block in result["content"]:
            if block.get("type") == "text":
                response_text += block.get("text", "")

    return response_text


def create_branch_and_commit(code_content: str, issue_number: int) -> str:
    """Create a new branch and commit the generated code."""
    branch_name = f"claude/issue-{issue_number}"

    try:
        # Configure git
        subprocess.run(["git", "config", "user.email", "claude@anthropic.com"], check=True)
        subprocess.run(["git", "config", "user.name", "Claude Bot"], check=True)

        # Fetch latest main
        subprocess.run(["git", "fetch", "origin", "main"], check=True)

        # Create and checkout new branch
        subprocess.run(["git", "checkout", "-b", branch_name, "origin/main"], check=True)

        # Save code to a file (assuming it's a code file)
        # For Tetris project, we'll determine the file type from content
        if "<!DOCTYPE" in code_content or "<html" in code_content:
            filename = "index.html"
        elif "function" in code_content and "{" in code_content and "}" in code_content:
            filename = "game.js"
        elif "css" in code_content or "color" in code_content:
            filename = "style.css"
        else:
            filename = "generated-code.js"

        # Write the code
        with open(filename, "w") as f:
            f.write(code_content)

        # Commit
        subprocess.run(["git", "add", filename], check=True)
        subprocess.run(
            ["git", "commit", "-m", f"Claude: Resolve issue #{issue_number}"],
            check=True
        )

        # Push
        subprocess.run(["git", "push", "origin", branch_name], check=True)

        return branch_name

    except subprocess.CalledProcessError as e:
        print(f"Git error: {e}", file=sys.stderr)
        raise


def create_pull_request(branch_name: str, issue_number: int, issue_title: str):
    """Create a PR for the generated code."""
    github_token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPOSITORY")

    if not github_token or not repo:
        raise ValueError("Missing GITHUB_TOKEN or GITHUB_REPOSITORY")

    pr_title = f"Claude: {issue_title} (Issue #{issue_number})"
    pr_body = f"""## Auto-generated PR by Claude Bot

**Resolves:** #{issue_number}

This PR was automatically generated by Claude based on the issue description.

### Changes
- Generated code to resolve the issue
- Implementation follows project conventions

This PR is ready for review and testing.

---
*Created by Claude via AWS Bedrock*"""

    try:
        subprocess.run(
            [
                "gh",
                "pr",
                "create",
                "--title",
                pr_title,
                "--body",
                pr_body,
                "--base",
                "main",
                "--head",
                branch_name,
                "--repo",
                repo,
            ],
            env={**os.environ, "GH_TOKEN": github_token},
            check=True,
        )
        print(f"PR created: {branch_name} → main")

    except subprocess.CalledProcessError as e:
        print(f"Error creating PR: {e}", file=sys.stderr)
        raise


def post_issue_comment(issue_number: int, message: str):
    """Post a comment on the GitHub issue."""
    github_token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPOSITORY")

    if not github_token or not repo:
        return

    try:
        subprocess.run(
            [
                "gh",
                "issue",
                "comment",
                str(issue_number),
                "--body",
                message,
                "--repo",
                repo,
            ],
            env={**os.environ, "GH_TOKEN": github_token},
            check=True,
        )
    except subprocess.CalledProcessError as e:
        print(f"Error posting comment: {e}", file=sys.stderr)


def main():
    issue_number = os.getenv("ISSUE_NUMBER")
    issue_title = os.getenv("ISSUE_TITLE")
    issue_body = os.getenv("ISSUE_BODY")

    if not issue_number or not issue_title:
        print("Missing issue information")
        return

    print(f"Processing issue #{issue_number}: {issue_title}")

    try:
        # Generate code
        print("Generating code with Claude...")
        code_content = generate_code_with_claude(issue_title, issue_body or "")

        if not code_content:
            raise ValueError("Claude did not generate any code")

        print("Code generated successfully")
        print(f"Generated {len(code_content)} characters")

        # Create branch and commit
        print("Creating branch and committing code...")
        branch_name = create_branch_and_commit(code_content, int(issue_number))

        # Create PR
        print("Creating pull request...")
        create_pull_request(branch_name, int(issue_number), issue_title)

        # Post comment on issue
        issue_comment = f"""✅ Claude has generated code to resolve this issue!

A PR has been created: [{branch_name}]({os.getenv('GITHUB_SERVER_URL')}/{os.getenv('GITHUB_REPOSITORY')}/pull)

Next steps:
1. Claude will review the generated code
2. If approved, you can review and merge the PR

---
*Generated by Claude Bot*"""

        post_issue_comment(int(issue_number), issue_comment)

        print("Done!")

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        post_issue_comment(
            int(issue_number),
            f"❌ Error generating code: {str(e)}"
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
