#!/usr/bin/env python3
"""
Post Claude's code review as a comment on the PR.
Reads the review from .review.json and posts it to GitHub.
"""

import json
import os
import sys
import subprocess


def post_comment_to_pr(review: str, pr_number: str, repo: str):
    """Post a comment to the PR using GitHub CLI."""
    try:
        comment_body = f"""## 🤖 Claude Code Review

{review}

---
*Review generated by Claude via AWS Bedrock*"""

        # Use gh CLI to post comment
        subprocess.run(
            [
                "gh",
                "pr",
                "comment",
                pr_number,
                "--body",
                comment_body,
                "--repo",
                repo,
            ],
            check=True,
            env={**os.environ, "GH_TOKEN": os.getenv("GITHUB_TOKEN", "")},
        )
        print(f"Comment posted to PR #{pr_number}")
    except subprocess.CalledProcessError as e:
        print(f"Error posting comment: {e}", file=sys.stderr)
        sys.exit(1)


def main():
    # Read review from file
    if not os.path.exists(".review.json"):
        print("No review file found. Skipping comment post.")
        return

    with open(".review.json", "r") as f:
        data = json.load(f)

    review = data.get("review", "")
    pr_number = data.get("pr_number") or os.getenv("PR_NUMBER")

    if not review or not pr_number:
        print("Missing review or PR number. Skipping comment post.")
        return

    repo = os.getenv("GITHUB_REPOSITORY", "")
    if not repo:
        print("Missing GITHUB_REPOSITORY. Skipping comment post.")
        return

    print(f"Posting review to PR #{pr_number}...")
    post_comment_to_pr(review, pr_number, repo)

    # Clean up
    os.remove(".review.json")
    print("Cleanup completed.")


if __name__ == "__main__":
    main()
